# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('component_type', models.IntegerField(choices=[(1, 'HTML'), (2, 'Problem'), (3, 'Video'), (4, 'Discussion')])),
                ('component_sub_type', models.IntegerField(choices=[(1, 'HTML > Raw HTML'), (31, 'Problem > Checkboxes(multi select)'), (32, 'Problem > Multiple choice(Select only one)')])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
